import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { React, useState, useEffect } from 'react'

const apikey = process.env.NEXT_DEEPGRAM_APIKEY

export async function getStaticProps() {
    const res_in_fr = await fetch(
        'https://api.deepgram.com/v1/listen?language=fr&model=general&punctuate=true',
        {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Authorization: `Token ${apikey}`,
            },
            body: JSON.stringify({
                url: 'https://www.lightbulblanguages.co.uk/resources/audio/quelageastu.mp3',
            }),
        }
    )
    const fr_data = await res_in_fr.json()
    return {
        props: { fr_data }, // will be passed to the page component as props
    }
}
// Static site generation ● / (1172 ms)
export default function Home(props) {
    // const [data, setData] = useState(null)
    // const [isLoading, setLoading] = useState(false)

    // useEffect(() => {
    //     setLoading(true)
    //     fetch(
    //         'https://api.deepgram.com/v1/listen?language=fr&model=general&punctuate=true',
    //         {
    //             method: 'POST',
    //             headers: {
    //                 'Content-Type': 'application/json',
    //                 Authorization: `Token VISIBLE KEY`,
    //             },
    //             body: JSON.stringify({
    //                 url: 'https://www.lightbulblanguages.co.uk/resources/audio/quelageastu.mp3',
    //             }),
    //         }
    //     )
    //         .then((res) => res.json())
    //         .then((data) => {
    //             setData(data)
    //             setLoading(false)
    //         })
    // }, [])

    // if (isLoading) return <p>Loading...</p>
    // if (!data) return <p>No profile data</p>

    // return (
    //     <div>
    //         <h1>
    //             {data.fr_data.results.channels[0].alternatives[0].transcript}
    //         </h1>
    //     </div>
    // )

    return (
        <div className={styles.container}>
            <Head>
                <title>Next.js Sample App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <main className={styles.main}>
                <h1>DeepGram Response</h1>
                <div className={styles.card}>
                    <h2>French Sample</h2>
                    <p>
                        {
                            props.fr_data.results.channels[0].alternatives[0]
                                .transcript
                        }
                    </p>
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    )
}
