import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react'

export async function getServerSideProps(context) {
    const apikey = process.env.DEEPGRAM_APIKEY
    const res_in_en = await fetch(
        'https://api.deepgram.com/v1/listen?language=en-US&model=general&punctuate=true',
        {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Authorization: `Token ${apikey}`,
            },
            body: JSON.stringify({
                url: 'https://static.deepgram.com/examples/Bueller-Life-moves-pretty-fast.wav',
            }),
        }
    )

    const res_in_fr = await fetch(
        'https://api.deepgram.com/v1/listen?language=fr&model=general&punctuate=true',
        {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Authorization: `Token ${apikey}`,
            },
            body: JSON.stringify({
                url: 'https://www.lightbulblanguages.co.uk/resources/audio/quelageastu.mp3',
            }),
        }
    )

    const en_data = await res_in_en.json()
    const fr_data = await res_in_fr.json()

    if (!en_data) {
        return {
            notFound: true,
        }
    }
    console.log('FRENCH', fr_data)
    return {
        props: { en_data, fr_data }, // will be passed to the page component as props
    }
}
export default function Home(props) {
    console.log('PROPS', props.en_data.results.channels[0])
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>DeepGram Samples</h1>
                <h2>English Sample</h2>
                <p>
                    {
                        props.en_data.results.channels[0].alternatives[0]
                            .transcript
                    }
                </p>
                <h2>French Sample</h2>
                <p>
                    {
                        props.fr_data.results.channels[0].alternatives[0]
                            .transcript
                    }
                </p>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}
